name: fallenrobot
services:
  - name: fallenbot
    type: web
    build:
      type: docker
    env:
      - key: API_ID
        value: "21418386"
      - key: API_HASH
        value: "aeac46b1d123e82fe6dcb43b6a26cfae"
      - key: BOT_TOKEN
        value: "5653372716:AAHeOJrabkMq0oOO8DKYgrY3IhR4Xc1yabg"
    ports:
      - 8080
